# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=1000)),
                ('descriptions', models.TextField(blank=True)),
                ('street', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('price', models.IntegerField(default=0)),
                ('number_of_bedrooms', models.IntegerField(default=0)),
                ('number_of_bathrooms', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('min_budget', models.IntegerField(default=0)),
                ('max_budget', models.IntegerField(default=0)),
                ('min_bedrooms', models.IntegerField(default=0)),
                ('max_bedrooms', models.IntegerField(default=0)),
                ('min_bathrooms', models.IntegerField(default=0)),
                ('max_bathrooms', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('mail_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Agentdesks.User'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Agentdesks.User'),
        ),
    ]
